language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - yarn install
services:
  - mongodb
env:
  global:
    - CC_TEST_REPORTER_ID=f3bc196a9076574e74ade7faa6e884683aa43121a4b089c616671715ec649beb
script:
  - yarn run test
after_script:
  - npm run coverage